name: paws
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.2.*
  - torchvision=0.17.*
  - torchaudio=2.2.*
  - pip
  - jax
  - pip:
    # --- Deep Learning / ML ---
    - timm
    
    # --- Reinforcement Learning / Robotics Environments ---
    - gymnasium[mujoco]
    - gymnasium-robotics
    - panda-gym
    - dm_control
    - metaworld
    - minigrid
    - robot_descriptions

    # --- RL Algorithms ---
    - stable-baselines3

    # --- Compute / Simulation ---
    - mujoco
    - warp-lang

    # --- Utilities (Config, Logging, Linting) ---
    - hydra-core
    - tensorboard
    - ruff

    # --- Commented / Unused / External ---
    # - opencv-python
    # - pytorchrl
    # - imitation
    # - openpose # Requires manual installation or build from source on Mac
    # - git+https://github.com/TRI-ML/prismatic-vlms.git
    # - https://github.com/google-deepmind/mujoco_menagerie
    # - git+https://github.com/stepjam/RLBench.git
    # - add Netown (Nvidia)
