experiment_name: fetch_pick_and_place

env:
  _target_: gymnasium.make
  id: FetchPickAndPlace-v4
  max_episode_steps: 50
  render_mode: null

model:
  _target_: paws.scripts.train_helper.make_sac_her
  experiment_name: ${experiment_name}
  policy: "MultiInputPolicy"
  learning_rate: 1e-3
  buffer_size: 1000000
  batch_size: 256
  gamma: 0.95
  n_sampled_goal: 4
  goal_selection_strategy: "future"
  net_arch: [256, 256, 256]
  device: "auto"
  verbose: 1

training:
  timesteps: 1000
  model_dir: models/${experiment_name}

evaluation:
  run_name: null
